CREATE TABLE "TASKER"."PERSON"
   (	"ID" NUMBER NOT NULL ENABLE,
	"USER_ID" VARCHAR2(32) NOT NULL ENABLE,
	"ADMINISTRATOR_ID" NUMBER,
	"CHANGE_DATE" DATE NOT NULL ENABLE,
	"CHANGE_USER" VARCHAR2(32) NOT NULL ENABLE,
	"FULL_NAME" VARCHAR2(1000),
	"PREF_NAME" VARCHAR2(255),
	 CONSTRAINT "PERSON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER"  ENABLE,
	 CONSTRAINT "PERSON_UKUSERID1" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER";

CREATE TABLE "TASKER"."ROLES"
   (	"ID" VARCHAR2(32) NOT NULL ENABLE,
	"PRIVILEGE" VARCHAR2(255) NOT NULL ENABLE,
	"GRANTED" VARCHAR2(1) NOT NULL ENABLE,
	 CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID", "PRIVILEGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER";

CREATE TABLE "TASKER"."SESSIONS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"USER_ID" VARCHAR2(32) NOT NULL ENABLE,
	"TOKEN" VARCHAR2(4000) NOT NULL ENABLE,
	"EXPIRY" DATE NOT NULL ENABLE,
	"HMAC_SECRET" VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER";

CREATE TABLE "TASKER"."SETTINGS"
   (	"ID" VARCHAR2(255) NOT NULL ENABLE,
	"VALUE" VARCHAR2(255),
	 CONSTRAINT "SETTINGS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER";

  CREATE TABLE "TASKER"."TASK"
   (	"ID" NUMBER NOT NULL ENABLE,
	"TITLE" VARCHAR2(4000) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(4000),
	"PCT_COMPLETE" NUMBER NOT NULL ENABLE,
	"STATUS" VARCHAR2(1) NOT NULL ENABLE,
	"OWNER" NUMBER NOT NULL ENABLE,
	"ASSIGNED_TO" NUMBER,
	"CHANGE_DATE" DATE NOT NULL ENABLE,
	"CHANGE_USER" VARCHAR2(32) NOT NULL ENABLE,
	 CONSTRAINT "TASK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER"  ENABLE,
	 CONSTRAINT "TASK_CHKSTATUS1" CHECK (STATUS IN ('I', 'C', 'H', 'X')) ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER";

  CREATE TABLE "TASKER"."TASK_COMMENTS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"TASK" NUMBER NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(4000) NOT NULL ENABLE,
	"CHANGE_DATE" DATE NOT NULL ENABLE,
	"CHANGE_USER" VARCHAR2(32) NOT NULL ENABLE,
	"AUTHOR" VARCHAR2(32)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER";

  CREATE TABLE "TASKER"."USERS"
   (	"ID" VARCHAR2(32) NOT NULL ENABLE,
	"EXTERNAL_AUTH_SYS" NUMBER,
	"EXTERNAL_AUTH_ID" VARCHAR2(256),
	"PASSWORD" VARCHAR2(4000),
	"SALT" VARCHAR2(4000),
	"STATUS" VARCHAR2(1) NOT NULL ENABLE,
	"CHANGE_DATE" DATE NOT NULL ENABLE,
	"CHANGE_USER" VARCHAR2(32) NOT NULL ENABLE,
	"FAILED_LOGIN_ATTEMPTS" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE,
	"ITER" NUMBER NOT NULL ENABLE,
	"LEN" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER"  ENABLE,
	 CONSTRAINT "USERS_CHKEXTVSINT1" CHECK ((EXTERNAL_AUTH_ID IS NOT NULL AND EXTERNAL_AUTH_SYS IS NOT NULL AND PASSWORD IS NULL AND SALT IS NULL) OR (EXTERNAL_AUTH_ID IS NULL AND EXTERNAL_AUTH_SYS IS NULL AND PASSWORD IS NOT NULL AND SALT IS NOT NULL)) ENABLE,
	 CONSTRAINT "USERS_CHKSTATUS1" CHECK (STATUS IN ('A', 'I')) ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER";

  CREATE TABLE "TASKER"."USER_ROLES"
   (	"USER_ID" VARCHAR2(32) NOT NULL ENABLE,
	"ROLE_ID" VARCHAR2(255) NOT NULL ENABLE,
	"CHANGE_DATE" DATE NOT NULL ENABLE,
	"CHANGE_USER" VARCHAR2(32),
	 CONSTRAINT "USER_ROLES_PK" PRIMARY KEY ("USER_ID", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASKER";










