CREATE OR REPLACE TRIGGER BI_PERSON_SEQ
BEFORE INSERT ON PERSON
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  IF :new.ID IS NULL THEN
    :new.ID := PERSON_SEQ.nextval();
  END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_TASK_SEQ
BEFORE INSERT ON TASK
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  IF :new.ID IS NULL THEN
    :new.ID := TASK_SEQ.nextval();
  END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_TASK_COMMENTS_SEQ
BEFORE INSERT ON TASK_COMMENTS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  IF :new.ID IS NULL THEN
    :new.ID := TASK_COMMENT_SEQ.nextval();
  END IF;
END;
/
