          headers:
            x-auth-token:
              description: |
                Authorization token to use on next request. If this token is not utilized, the request will always fail.
              example: |
                1234.C483918E193FBCAA2391038E103850F10389AAC9481C938999A