      queryParameters:
        page:
          description: Desired page to retrieve; `0` if not supplied.
          example: 12
        pageSize:
          description: Number of items on a page; default is based on server settings
          example: 25
